#cloud-config
package_update: true
packages:
  - nodejs
  - npm

write_files:
  - path: /home/azureuser/frontend-app/.env
    content: |
      BFF_URL=${BFF_URL}
  - path: /home/azureuser/frontend-app/app.js
    content: |
      const express = require('express');
      const path = require('path');
      const multer = require('multer');
      const axios = require('axios');
      const fs = require('fs');
      const FormData = require('form-data');
      require('dotenv').config();
      const app = express();
      const upload = multer({ dest: 'uploads/' });
      const PORT = process.env.PORT || 3001;
      const BFF_URL = process.env.BFF_URL;

      // Serve React static files
      app.use(express.static(path.join(__dirname, 'build')));

      // File upload endpoint
      app.post('/upload', upload.single('file'), async (req, res) => {
        const file = req.file;
        const formData = new FormData();
        formData.append('file', fs.createReadStream(file.path), file.originalname);
        try {
          await axios.post(`${BFF_URL}/process`, formData, { headers: formData.getHeaders() });
          res.json({ message: 'File uploaded and sent to BFF!' });
        } catch (err) {
          res.status(500).json({ error: 'Error sending file to BFF' });
        }
      });

      // Fallback to index.html for SPA
      app.get('*', (req, res) => {
        res.sendFile(path.join(__dirname, 'build', 'index.html'));
      });

      app.listen(PORT, () => {
        console.log(`Frontend server running on port ${PORT}`);
      });
  - path: /home/azureuser/frontend-app/package.json
    content: |
      {
        "name": "frontend-app",
        "version": "1.0.0",
        "main": "app.js",
        "dependencies": {
          "express": "^4.18.2",
          "multer": "^1.4.5",
          "axios": "^1.6.0",
          "dotenv": "^16.0.3",
          "form-data": "^4.0.0"
        },
        "scripts": {
          "start": "node app.js",
          "build": "cd react-src && npm install && npm run build && cp -r build ../build"
        }
      }
  - path: /home/azureuser/frontend-app/react-src/package.json
    content: |
      {
        "name": "react-src",
        "version": "1.0.0",
        "private": true,
        "dependencies": {
          "react": "^18.2.0",
          "react-dom": "^18.2.0",
          "react-scripts": "5.0.1"
        },
        "scripts": {
          "start": "react-scripts start",
          "build": "react-scripts build"
        }
      }
  - path: /home/azureuser/frontend-app/react-src/src/App.js
    content: |
      import React, { useState } from 'react';

      function App() {
        const [file, setFile] = useState(null);
        const [message, setMessage] = useState('');

        const handleFileChange = (e) => {
          setFile(e.target.files[0]);
        };

        const handleSubmit = async (e) => {
          e.preventDefault();
          if (!file) return;
          const formData = new FormData();
          formData.append('file', file);
          try {
            const res = await fetch('/upload', {
              method: 'POST',
              body: formData
            });
            const data = await res.json();
            setMessage(data.message || data.error);
          } catch (err) {
            setMessage('Upload failed');
          }
        };

        return (
          <div style={{ padding: 40 }}>
            <h2>Upload a File</h2>
            <form onSubmit={handleSubmit}>
              <input type="file" onChange={handleFileChange} />
              <button type="submit">Upload</button>
            </form>
            {message && <p>{message}</p>}
          </div>
        );
      }

      export default App;
  - path: /home/azureuser/frontend-app/react-src/src/index.js
    content: |
      import React from 'react';
      import ReactDOM from 'react-dom/client';
      import App from './App';

      const root = ReactDOM.createRoot(document.getElementById('root'));
      root.render(
        <React.StrictMode>
          <App />
        </React.StrictMode>
      );
  - path: /home/azureuser/frontend-app/react-src/public/index.html
    content: |
      <!DOCTYPE html>
      <html lang="en">
      <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>File Upload Frontend</title>
      </head>
      <body>
        <div id="root"></div>
      </body>
      </html>

runcmd:
  - cd /home/azureuser/frontend-app/react-src
  - npm install
  - npm run build
  - cd ..
  - npm install
  - export BFF_URL=http://<BFF_VM_IP>:4000
  - nohup node app.js &
