#cloud-config
package_update: true
packages:
  - nodejs
  - npm

write_files:
  - path: /home/azureuser/bff-app/app.js
    content: |
      const express = require('express');
      const app = express();
      const port = process.env.PORT || 3000;

      app.get('/', (req, res) => {
        res.send('BFF is running');
      });

      app.listen(port, () => console.log(`BFF running on port ${port}`));
  - path: /home/azureuser/bff-app/package.json
    content: |
      {
        "name": "bff-app",
        "version": "1.0.0",
        "main": "app.js",
        "dependencies": {
          "express": "^4.18.2"
        }
      }

runcmd:
  - mkdir -p /home/azureuser/bff-app
  - cd /home/azureuser/bff-app
  - npm install
  - nohup node app.js &
