#cloud-config
package_update: true
packages:
  - mariadb-server

runcmd:
  - systemctl start mariadb
  - systemctl enable mariadb
  - mysql -u root -e "CREATE DATABASE appdb;"
  - mysql -u root -e "CREATE USER 'appuser'@'%' IDENTIFIED BY 'yourpassword';"
  - mysql -u root -e "GRANT ALL PRIVILEGES ON appdb.* TO 'appuser'@'%';"
  - mysql -u root -e "FLUSH PRIVILEGES;"
  - mysql -u root appdb -e "CREATE TABLE uploads (id INT AUTO_INCREMENT PRIMARY KEY, filename VARCHAR(255) NOT NULL, uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);"
