#cloud-config
package_update: true
packages:
  - nodejs
  - npm

write_files:
  - path: /home/azureuser/bff-app/app.js
    content: |
      const express = require('express');
      const mysql = require('mysql2/promise');
      const app = express();
      DB_CONNECTION_STRING=mysql://appuser:yourpassword@${DB_IP}/appdb
      const port = process.env.PORT || 3000;

      app.get('/', (req, res) => {
        res.send('BFF is running');
      });

      app.get('/healthz', (req, res) => {
        let dbStatus = 'unreachable';
        mysql.createConnection(DB_CONNECTION_STRING)
          .then(connection => {
            dbStatus = 'reachable';
            connection.end();
          })
          .catch(err => {
            console.error('Database connection error:', err);
          });


        res.send(`BFF is healthy. DB status: ${dbStatus}`);
      });

      app.listen(port, () => console.log(`BFF running on port ${port}`));
  - path: /home/azureuser/bff-app/package.json
    content: |
      {
        "name": "bff-app",
        "version": "1.0.0",
        "main": "app.js",
        "dependencies": {
          "express": "^4.18.2",
          "mysql2": "^3.2.0"
        }
      }

runcmd:
  - export BLOB_CONNECTION_STRING=<set your blob connection string>
  - export DB_IP=<set your database IP address>
  - mkdir -p /home/azureuser/bff-app
  - cd /home/azureuser/bff-app
  - npm install
  - nohup node app.js &
