#cloud-config
package_update: true
packages:
  - nodejs
  - npm

write_files:
  - path: /home/azureuser/frontend-app/app.js
    content: |
      const express = require('express');
      const app = express();
      const port = process.env.PORT || 3001;

      app.get('/', (req, res) => {
        res.send('Frontend is running');
      });

      app.listen(port, () => console.log(`Frontend running on port ${port}`));
  - path: /home/azureuser/frontend-app/package.json
    content: |
      {
        "name": "frontend-app",
        "version": "1.0.0",
        "main": "app.js",
        "dependencies": {
          "express": "^4.18.2"
        },
        "scripts": {
          "start": "node app.js"
        }
      }

runcmd:
  - mkdir -p /home/azureuser/frontend-app
  - cd /home/azureuser/frontend-app
  - npm install
  - nohup node app.js &
